package com.itheima.prize.commons.db.mapper;

import com.itheima.prize.commons.db.entity.SysUser;
import com.itheima.prize.commons.db.entity.SysUserExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

@Mapper
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    long countByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int deleteByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sys_user",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sys_user (username, realname, ",
        "password, salt, ",
        "avatar, birthday, ",
        "sex, email, phone, ",
        "org_code, status, ",
        "del_flag, third_id, ",
        "third_type, activiti_sync, ",
        "work_no, telephone, ",
        "create_by, create_time, ",
        "update_by, update_time, ",
        "user_identity, depart_ids, ",
        "client_id, login_tenant_id, ",
        "bpm_status)",
        "values (#{username,jdbcType=VARCHAR}, #{realname,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{salt,jdbcType=VARCHAR}, ",
        "#{avatar,jdbcType=VARCHAR}, #{birthday,jdbcType=TIMESTAMP}, ",
        "#{sex,jdbcType=TINYINT}, #{email,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR}, ",
        "#{orgCode,jdbcType=VARCHAR}, #{status,jdbcType=TINYINT}, ",
        "#{delFlag,jdbcType=TINYINT}, #{thirdId,jdbcType=VARCHAR}, ",
        "#{thirdType,jdbcType=VARCHAR}, #{activitiSync,jdbcType=TINYINT}, ",
        "#{workNo,jdbcType=VARCHAR}, #{telephone,jdbcType=VARCHAR}, ",
        "#{createBy,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{userIdentity,jdbcType=TINYINT}, #{departIds,jdbcType=VARCHAR}, ",
        "#{clientId,jdbcType=VARCHAR}, #{loginTenantId,jdbcType=INTEGER}, ",
        "#{bpmStatus,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=String.class)
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    List<SysUser> selectByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, username, realname, password, salt, avatar, birthday, sex, email, phone, ",
        "org_code, status, del_flag, third_id, third_type, activiti_sync, work_no, telephone, ",
        "create_by, create_time, update_by, update_time, user_identity, depart_ids, client_id, ",
        "login_tenant_id, bpm_status",
        "from sys_user",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("com.itheima.prize.commons.db.mapper.SysUserMapper.BaseResultMap")
    SysUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated
     */
    @Update({
        "update sys_user",
        "set username = #{username,jdbcType=VARCHAR},",
          "realname = #{realname,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "salt = #{salt,jdbcType=VARCHAR},",
          "avatar = #{avatar,jdbcType=VARCHAR},",
          "birthday = #{birthday,jdbcType=TIMESTAMP},",
          "sex = #{sex,jdbcType=TINYINT},",
          "email = #{email,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "org_code = #{orgCode,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=TINYINT},",
          "del_flag = #{delFlag,jdbcType=TINYINT},",
          "third_id = #{thirdId,jdbcType=VARCHAR},",
          "third_type = #{thirdType,jdbcType=VARCHAR},",
          "activiti_sync = #{activitiSync,jdbcType=TINYINT},",
          "work_no = #{workNo,jdbcType=VARCHAR},",
          "telephone = #{telephone,jdbcType=VARCHAR},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "user_identity = #{userIdentity,jdbcType=TINYINT},",
          "depart_ids = #{departIds,jdbcType=VARCHAR},",
          "client_id = #{clientId,jdbcType=VARCHAR},",
          "login_tenant_id = #{loginTenantId,jdbcType=INTEGER},",
          "bpm_status = #{bpmStatus,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysUser record);
    @Select("select * from sys_user where username=#{username}")
    SysUser selectByName(String username);
}
