package com.itheima.prize.commons.db.entity;

import java.io.Serializable;

public class CardGameProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_game_product.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_game_product.gameid
     *
     * @mbg.generated
     */
    private String gameid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_game_product.productid
     *
     * @mbg.generated
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_game_product.amount
     *
     * @mbg.generated
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_game_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_game_product.id
     *
     * @return the value of card_game_product.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_game_product.id
     *
     * @param id the value for card_game_product.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_game_product.gameid
     *
     * @return the value of card_game_product.gameid
     *
     * @mbg.generated
     */
    public String getGameid() {
        return gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_game_product.gameid
     *
     * @param gameid the value for card_game_product.gameid
     *
     * @mbg.generated
     */
    public void setGameid(String gameid) {
        this.gameid = gameid == null ? null : gameid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_game_product.productid
     *
     * @return the value of card_game_product.productid
     *
     * @mbg.generated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_game_product.productid
     *
     * @param productid the value for card_game_product.productid
     *
     * @mbg.generated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_game_product.amount
     *
     * @return the value of card_game_product.amount
     *
     * @mbg.generated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_game_product.amount
     *
     * @param amount the value for card_game_product.amount
     *
     * @mbg.generated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}