package com.itheima.prize.commons.db.entity;

import com.alibaba.fastjson.JSON;

import java.io.Serializable;
import java.lang.reflect.Field;
import java.util.Date;

public class CardUserGame implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_user_game.id
     *
     * @mbg.generated
     */
    private Integer id;



    public Integer getUserid() {
        return userid;
    }


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_user_game.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_user_game.gameid
     *
     * @mbg.generated
     */
    private Integer gameid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_user_game.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_user_game
     *
     * @mbg.generated
     */

    public CardUserGame(){}

    public CardUserGame(Integer userid, Integer gameid, Date createtime) {
        this.userid = userid;
        this.gameid = gameid;
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_user_game.id
     *
     * @return the value of card_user_game.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_user_game.id
     *
     * @param id the value for card_user_game.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_user_game.userid
     *
     * @return the value of card_user_game.userid
     *
     * @mbg.generated
     */
    public Integer getUserid(Integer id) {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_user_game.userid
     *
     * @param userid the value for card_user_game.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_user_game.gameid
     *
     * @return the value of card_user_game.gameid
     *
     * @mbg.generated
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_user_game.gameid
     *
     * @param gameid the value for card_user_game.gameid
     *
     * @mbg.generated
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_user_game.createtime
     *
     * @return the value of card_user_game.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_user_game.createtime
     *
     * @param createtime the value for card_user_game.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public static void main(String[] args) {
        CardUserGame game = JSON.parseObject("{\"gameid\":10,\"hittime\":1701848258856,\"userid\":10}",CardUserGame.class);
//        game.setUserid(123);
//        game.setGameid(222);
//        CardUserGame game = new CardUserGame(20,20,new Date());
//        CardUserHit hit = new CardUserHit(10,10,10,new Date());
//        game.setUserid(100);


       Field[] aa = CardUserGame.class.getDeclaredFields();
        System.out.println(JSON.toJSONString(game));
//        System.out.println(JSON.toJSONString(hit));
    }
}